version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: dev_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: simt_user
      POSTGRES_PASSWORD: simtDev@2025!
      POSTGRES_DB: simt_dev
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: dev_server
    restart: "no"
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: air
